// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Drawing;

namespace MemcardRex
{
	public partial class CommentDialogController : NSViewController
	{
        #region Private Variables
        private string _dialogTitle = "";
        private string _comment = "";
        private NSViewController _presentor;
        #endregion

        #region Computed Properties
        public string DialogTitle
        {
            get { return _dialogTitle; }
            set { _dialogTitle = value; }
        }

        public string Comment
        {
            get { return _comment; }
            set { _comment = value; }
        }

        public NSViewController Presentor
        {
            get { return _presentor; }
            set { _presentor = value; }
        }
        #endregion

        public CommentDialogController (IntPtr handle) : base (handle)
		{
		}

        #region Override Methods
        public override void ViewWillAppear()
        {
            base.ViewWillAppear();

            this.View.Window.Title = DialogTitle;

            CommentTextInput.StringValue = Comment;


            //Disable resizing of modal dialog
            this.View.Window.StyleMask &= ~NSWindowStyle.Resizable;
        }
        #endregion

        #region Events
        public EventHandler DialogAccepted;

        internal void RaiseDialogAccepted()
        {
            if (this.DialogAccepted != null)
                this.DialogAccepted(this, EventArgs.Empty);
        }
        #endregion

        [Export("ConfirmDialog:")]
        void AcceptDialog(NSObject sender)
        {
            //Save changes
            Comment = CommentTextInput.StringValue;

            RaiseDialogAccepted();
            Presentor.DismissViewController(this);
        }

        [Export("CancelDialog:")]
        void CancelDialoga(NSObject sender)
        {
            Presentor.DismissViewController(this);
        }
    }
}
